CREATE TABLE USUARIO(
	ID_USUARIO NUMBER CONSTRAINT ID_USUARIO_PK PRIMARY KEY,
	NOME VARCHAR2(40) CONSTRAINT NN_NOME_USUARIO NOT NULL,
	SENHA VARCHAR2(40) CONSTRAINT NN_SENHA NOT NULL,
	CPF NUMBER CONSTRAINT UN_CPF_USUARIO UNIQUE
	ID_ENDERECO_USUARIO_FK NUMBER,
	CONSTRAINT ENDERECO_ID_ENDERECO_USUARIO_FK FOREIGN KEY(ID_ENDERECO_USUARIO_FK) REFERENCES ENDERECO(ID_ENDERECO)
);

CREATE TABLE CLIENTE(
	ID_CLIENTE NUMBER CONSTRAINT ID_CLIENTE_PK PRIMARY KEY,
	NOME VARCHAR2(40) CONSTRAINT NN_NOME_CLIENTE NOT NULL,
	CPF NUMBER CONSTRAINT UN_CPF_CLIENTE UNIQUE
	ID_ENDERECO_CLIENTE_FK NUMBER,
	CONSTRAINT ENDERECO_ID_ENDERECO_CLIENTE_FK FOREIGN KEY(ID_ENDERECO_CLIENTE_FK) REFERENCES ENDERECO(ID_ENDERECO)	
);

CREATE TABLE CIDADE(
	ID_CIDADE NUMBER CONSTRAINT ID_CIDADE_PK PRIMARY KEY,
	NOME VARCHAR2(40) CONSTRAINT NN_CIDADE NOT NULL,
	SIGLA VARCHAR2(02) CONSTRAINT NN_SIGLA NOT NULL,
	CONSTRAINT UN_SIGLA UNIQUE(SIGLA)
);

CREATE TABLE ENDERECO(
	ID_ENDERECO NUMBER CONSTRAINT ID_ENDERECO_PK PRIMARY KEY,
	RUA VARCHAR2(40) CONSTRAINT NN_RUA NOT NULL,
	NUMERO NUMBER,
	COMPLEMENTO VARCHAR2(40),
	CEP NUMBER
	ID_CIDADE_ENDERECO_FK NUMBER,
	CONSTRAINT CIDADE_ID_CIDADE_ENDERECO_FK FOREIGN KEY (ID_CIDADE_ENDERECO_FK) REFERENCES CIDADE(ID_CIDADE),	
);

CREATE TABLE RECIBO(
	ID_RECIBO NUMBER CONSTRAINT ID_RECIBO_PK PRIMARY KEY,
	VALOR NUMBER,
	DATARECIBO DATE,
	ASSINATURA VARCHAR2(40) CONSTRAINT NN_ASSINATURA NOT NULL,
	REFERENTE VARCHAR2(40) CONSTRAINT NN_REFERENTE NOT NULL,
	ID_CIDADE_RECIBO_FK NUMBER,
	ID_USUARIO_RECIBO_FK NUMBER,
	ID_CLIENTE_RECIBO_FK NUMBER,
	CONSTRAINT CIDADE_ID_CIDADE_RECIBO_FK FOREIGN KEY (ID_CIDADE_RECIBO_FK) REFERENCES CIDADE(ID_CIDADE),
	CONSTRAINT USUARIO_ID_USUARIO_RECIBO_FK FOREIGN KEY (ID_USUARIO_RECIBO_FK) REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT CLIENTE_ID_CLIENTE_RECIBO_FK FOREIGN KEY (ID_CLIENTE_RECIBO_FK) REFERENCES CLIENTE(ID_CLIENTE)	
);