-- Exercício 1
insert into 
	public.uf(nome, sigla)
values
	('Acre','AC'),
	('Alagoas','AL'),
	('Amapá','AP'),
	('Amazonas','AM'),
	('Bahia','BA'),
	('Ceará','CE'),
	('Distrito Federal','DF'),
	('Espírito Santo','ES'),
	('Goiás','GO'),
	('Maranhão','MA'),
	('Mato Grosso','MT'),
	('Mato Grosso Do Sul','MS'),
	('Minas Gerais','MG'),
	('Pará','PA'),
	('Paraíba','PB'),
	('Paraná','PR'),
	('Pernambuco','PE'),
	('Piauí','PI'),
	('Roraima','RR'),
	('Rondônia','RO'),
	('Rio De Janeiro','RJ'),
	('Rio Grande Do Norte','RN'),
	('Rio Grande Do Sul','RS'),
	('Santa Catarina','SC'),
	('São Paulo','SP'),
	('Sergipe','SE'),
	('Tocantis','TO');

-- Exercício 2
-- SC = 24, PR = 16, SP = 25
insert into 
	public.cidade(id_uf, nome)
values
	('24','Chapecó'),
	('24','Blumenau'),
	('24','Joinvile'),
	('16','Curitiba'),
	('16','Maringá'),
	('16','Lunardeli'),
	('16','Apucarana'),
	('16','Santa Fé'),
	('16','São Miguel Do Iguaçu'),
	('16','Arapongas'),
	('16','Ponta Grossa'),
	('16','Jandaia Do Sul'),
	('25','Ribeirão Preto');

-- Exercício 3
-- Gambiarra
delete from public.uf 
	where (sigla <> 'SC') 
	and (sigla <> 'PR') 
	and (sigla <> 'SP');

-- Exerício 4
insert into 
	public.cidade(id_uf, nome)
values
	('25','São Paulo'),
	('25','Campinas'),
	('25','Presidente Prudente');

-- Exercício 5
update public.cidade 
	set nome = 'Lunardelli' 
	where nome = 'Lunardeli'
	
update public.cidade 
	set nome = 'Jandaia' 
	where nome = 'Jandaia Do Sul'
	
update public.cidade 
	set nome = 'Cidade Canção' 
	where nome = 'Maringá'

-- Exercício 6
select cidade.nome, uf.nome
	from public.cidade, public.uf
	where cidade.id_uf = uf.id
	order by uf.nome asc;

select cidade.nome, uf.nome
	from public.cidade, public.uf
	where cidade.id_uf = uf.id
	order by cidade.nome asc;

-- Exercício 7
select uf.nome, count(cidade.id) as NumeroDeCidades 
	from public.uf, public.cidade
	where cidade.id_uf = uf.id
	group by uf.nome;

-- Exercício 8
create table tipo_endereco(
	id bigint not null generated by default as identity,
	tipo varchar(20),
	constraint tipo_endereco_pk primary key(id)
);

alter table public.endereco 
	add constraint id_tipo_endereco_fk
	foreign key (id_tipo_endereco)
	references public.tipo_endereco(id);

insert into 
	public.tipo_endereco(tipo)
values
	('Comercial'),
	('Residencial');

-- Exercício 9
insert into 
	public.pessoa(nome, cpf)
values
	('Pessoa1','11111111111'),
	('Pessoa2','22222222222'),
	('Pessoa3','33333333333');

insert into
	public.endereco(id_cidade, id_pessoa, logradouro, numero, cep, id_tipo_endereco)
values
	(4, 1, 'rua1', '1','11111111', 1),
	(4, 1, 'rua2', '2','11111111', 2),
	(7, 2, 'rua3', '3','22222222', 1),
	(7, 2, 'rua4', '4','22222222', 2),
	(8, 3, 'rua5', '5','33333333', 1),
	(8, 3, 'rua6', '6','33333333', 2);

-- Exercício 10
insert into 
	public.pessoa(nome, cpf)
values
	('Pessoa4','44444444444'),
	('Pessoa5','55555555555');

insert into
	public.endereco(id_cidade, id_pessoa, logradouro, numero, cep, id_tipo_endereco)
values
	(15, 4, 'rua7', '7','44444444', 1),
	(15, 4, 'rua8', '8','44444444', 2),
	(16, 5, 'rua9', '9','55555555', 1),
	(16, 5, 'rua10', '10','55555555', 2);
	
-- Exercício 11
insert into 
	public.pessoa(nome, cpf)
values
	('Pessoa6','66666666666'),
	('Pessoa7','77777777777');

insert into
	public.endereco(id_cidade, id_pessoa, logradouro, numero, cep, id_tipo_endereco)
values
	(1, 6, 'rua11', '11','66666666', 1),
	(2, 7, 'rua12', '12','77777777', 1);
	
-- Exercício 12
select pes.nome as Pessoa, cid.nome as Cidade, uf.nome as Estado, ende.logradouro, ende.numero, ende.cep
	from pessoa pes
	inner join endereco ende on(pes.id = ende.id_pessoa)
	inner join cidade cid on(cid.id = ende.id_cidade)
	inner join uf on(uf.id = cid.id_uf)
	order by pes.nome;

select pes.nome as Pessoa, cid.nome as Cidade, uf.nome as Estado, ende.logradouro, ende.numero, ende.cep
	from pessoa pes
	inner join endereco ende on(pes.id = ende.id_pessoa)
	inner join cidade cid on(cid.id = ende.id_cidade)
	inner join uf on(uf.id = cid.id_uf)
	order by cid.nome;

select pes.nome as Pessoa, cid.nome as Cidade, uf.nome as Estado, ende.logradouro, ende.numero, ende.cep
	from pessoa pes
	inner join endereco ende on(pes.id = ende.id_pessoa)
	inner join cidade cid on(cid.id = ende.id_cidade)
	inner join uf on(uf.id = cid.id_uf)
	order by uf.nome;

-- Exercício 13
delete from public.pessoa
	where exists
	( select ende.id_pessoa, ende.id_cidade 
	  	from endereco ende
	  		where ende.id_pessoa = ende.id_cidade
	  		and ende.id_cidade = 13);

-- Exercício 14
update public.endereco set cep = 00000000;

-- Exercício 15

insert into 
	public.pessoa(nome, cpf)
values
	('Fusca','1'),
	('Tamara','2');

insert into 
	public.pessoa(nome, cpf)
values
	('DB1','3'),
	('FCV','4'),
	('USP','5');

insert into
	public.endereco(id_cidade, id_pessoa, logradouro, numero, cep, id_tipo_endereco)
values
	(4, 8, 'rua qualquer 1', '50','100', 1),
	(5, 9, 'rua qualquer 2', '60','200', 1);

insert into
	public.endereco(id_cidade, id_pessoa, logradouro, numero, cep, id_tipo_endereco)
values
	(5, 10, 'rua qualquer 3', '70','300', 2),
	(5, 11, 'rua qualquer 4', '80','400', 2),
	(15, 12, 'rua qualquer 5', '90','500', 2);

insert into 
	public.recibo(id_cliente, id_emitente, id_cidade, sequencia, data, assinatura, valor)
values
	(8, 10, 5, 1, current_date, 'assinatura1', 500.00),
	(9, 10, 5, 2, current_date, 'assinatura2', 700.00);

select * from recibo;	
-- Exercício 16
insert into 
	public.recibo(id_cliente, id_emitente, id_cidade, sequencia, data, assinatura, valor)
values
	(8, 11, 5, 3, current_date, 'assinatura3', 900.00),
	(9, 12, 15, 4, current_date, 'assinatura4', 750.00);

-- Exercício 17
-- incompleto
select rec.sequencia as numero_recibo
	   rec.data as data_recibo,
	   rec.valor as valor_recibo,
	   cli.nome as nome_cliente,
	   cli.uf.nome as estado_cliente,
	   emi.uf.nome as nome_emitente,
	   emi.uf.nome as estado_emitente
	   from recibo rec 
	   inner join pessoa cli on(rec.id_cliente = cli.id)
	   inner join pessoa emi on(rec.id_cliente = emi.id);
	   
-- Exercício 18
-- a fazer.